repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
  - repo: https://github.com/openstack/bashate
    rev: 0.6.0
    hooks:
    - id: bashate
